apiVersion: v1
kind: ServiceAccount
metadata:
  name: streaming-sa
  namespace: streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::871007552317:role/risk-eks-streaming-s3-irsa-role
