apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-spark-fx
  namespace: streaming
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: "55 16 * * 0"
  timeZone: "America/New_York"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          restartPolicy: OnFailure
          serviceAccountName: streaming-sa
          containers:
            - name: start-fx
              image: "{{ .Values.image.kubectl.repository }}:{{ .Values.image.kubectl.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - kubectl -n streaming scale deployment spark-fx --replicas=1
