apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  namespace: airflow
spec:
  selector:
    app: airflow-worker
  ports:
    - name: logs
      port: 8793
      targetPort: 8793
  type: ClusterIP
