apiVersion: v1
kind: Service
metadata:
  name: airflow-worker-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: airflow-worker
  ports:
    - name: logs
      port: 8793
      targetPort: 8793