replicaCount: 1

image:
  repository: 922967232801.dkr.ecr.us-east-1.amazonaws.com/django
  tag: "1"
  pullPolicy: IfNotPresent

service:
  port: 8000

nodeSelector:
  role: web

envFrom:
  configMapName: django-config
  secretName: django-secret

ingress:
  enabled: true
  host: api.pushparag.online
  certificateArn: arn:aws:acm:us-east-1:922967232801:certificate/e0af3110-f363-4d3e-85a0-2e428d4cd4a6
  groupName: risk-engine
