replicaCount: 1

image:
  repository: 922967232801.dkr.ecr.us-east-1.amazonaws.com/nextjs
  tag: "1"
  pullPolicy: IfNotPresent

service:
  port: 3000

nodeSelector:
  role: web

envFrom:
  configMapName: nextjs-config

ingress:
  enabled: true
  host: app.pushparag.online
  certificateArn: arn:aws:acm:us-east-1:922967232801:certificate/e0af3110-f363-4d3e-85a0-2e428d4cd4a6
  groupName: risk-engine
