replicaCount: 1

image:
  repository: 871007552317.dkr.ecr.us-east-1.amazonaws.com/nextjs
  tag: "0"
  pullPolicy: IfNotPresent

service:
  port: 3000

nodeSelector:
  role: web

envFrom:
  configMapName: nextjs-config

ingress:
  enabled: true
  host: app.pushparag.online
  certificateArn: arn:aws:acm:us-east-1:871007552317:certificate/3ba64c9b-66cf-4dd6-b635-f92c1a8cdba9
  groupName: risk-engine
